---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBName: 
    Type: String
    Description: Database name
  DBUserName:
    Type: String
    Description: User name for DB instance
  DBPassword:
    Type: String
    Description: Password for DB instance
    NoEcho: true
Resources:
# Database
  RdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: rails-app-db
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !ImportValue RDSSGFromSecurityStack
      DBSubnetGroupName: !Ref RdsSubnetGroup
      Engine: MySQL
      EngineVersion: 8.0.23
      MasterUsername: !Ref DBUserName
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
  RdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Group for Rails App
      DBSubnetGroupName: RailsAppDBSubnetGroup
      SubnetIds:
        - !ImportValue PublicSubnet1aFromNetworkStack
        - !ImportValue PublicSubnet1cFromNetworkStack
